name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@db4d66086aa9d3bd57b1f854b998674ca9846f7d
        with: 
            owner: NamrataJha
            repo: debug-action
            package-name: debug-action
            min-versions-to-keep: 50

 


          
