name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix: 
        node: ["debug-action"]
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@v2
        with: 
            owner: NamrataJha
            repo: 'debug-action'
            package-name: ${{ matrix.node }}
            min-versions-to-keep: 50


 


          
