name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        node: ["debug-action", "npm-action-test", "test-repo", "sample"]
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@v2
        with: 
            owner: NamrataJha
            repo: ${{ matrix.node }}
            package-name: ${{ matrix.node }}
            min-versions-to-keep: 50
            token: ${{ secrets.PAT }}


 


          
