name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
      - run: bundle config set rubygems.pkg.github.com Drowze:${{ secrets.PERSONAL_TOKEN }}
      - run: bundle -V
